plugins {
    id 'com.android.application'
}

android {
    namespace 'jp.gazou.viewer'
    compileSdk 36

    defaultConfig {
        applicationId 'jp.gazou.viewer'
        minSdk 28
        targetSdk 33
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
